CRUDWithAccounts/Models/ErrorViewModel.cs
namespace CRUDWithAccounts.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

CRUDWithAccounts/ViewModels/DiskViewModel.cs
namespace CRUDWithAccounts.ViewModels;

public class DiskViewModel
{
    public string Manufacturer { get; set; }
    public string Model { get; set; }
    public string Type { get; set; }
    public int Capacity { get; set; }
    public int? ReadSpeed { get; set; }
    public int? WriteSpeed { get; set; }
    public int Cost { get; set; }
}

CRUDWithAccounts/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CRUDWithAccounts.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        public string Username { get; set; }
        [Required]
        public string Password { get; set; }
    }
}

CRUDWithAccounts/ViewModels/UserWithRoleViewModel.cs
namespace CRUDWithAccounts.ViewModels;

public class UserWithRoleViewModel
{
    public string Username { get; set; }
    public string Role { get; set; }
}

CRUDWithAccounts/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using Database;
using Database.Entity;
using Database.Enum;
using CRUDWithAccounts.ViewModels;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using CRUDWithAccounts.Helpers;
using Microsoft.AspNetCore.Authorization;

namespace CRUDWithAccounts.Controllers;

public class AccountController : Controller
{
    private readonly ILogger<AccountController> _logger;
    private readonly IDBRepository repository;

    public AccountController(ILogger<AccountController> logger, IDBRepository _repository)
    {
        _logger = logger;
        repository = _repository;
    }
  
    public IActionResult Login()
    {
        return View();
    }
    
    [HttpPost]
    public async Task<IActionResult> Login(LoginViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View();
        }

        var foundAccount = await repository.FindAccountAsync(model.Username, HashPasswordHelper.HashPassword(model.Password));

        if (foundAccount is not null)
        {
            if (foundAccount.Login == model.Username && foundAccount.Password == HashPasswordHelper.HashPassword(model.Password))
            {
                return await customLogin(model.Username, foundAccount.Role);
            }
            else
            {
                return View();
            }
        }
        else
        {
            var accountToAdd = new Account() {
                Login = model.Username,
                Password = HashPasswordHelper.HashPassword(model.Password),
                Role = Database.Enum.Role.User
            };
            await repository.AddAccountAsync(accountToAdd);
            return await customLogin(model.Username, Role.User);
        }
        
    }

    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync("Cookie");
        return Redirect("/");
    }

    private async Task<IActionResult> customLogin(string username, Role role)
    {
        var claims = new List<Claim>
        {
            new Claim(ClaimTypes.Name, username),
            new Claim(ClaimTypes.Role, role.ToString())
        };
        var claimIdentity = new ClaimsIdentity(claims, "Cookie");
        var claimPrincipal = new ClaimsPrincipal(claimIdentity);
        await HttpContext.SignInAsync("Cookie", claimPrincipal);

        return RedirectToAction("Index", "Home");
    }

}

CRUDWithAccounts/Controllers/AccountPageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Database.Entity;
using CRUDWithAccounts.ViewModels;

namespace CRUDWithAccounts.Controllers;

[Authorize(Roles = "User")]
public class AccountPageController : Controller
{
    public IActionResult AccountPage() 
    {
        var userViewModel = new UserWithRoleViewModel();
        userViewModel.Username = User.Identity.Name;
        var claims = ((ClaimsIdentity)User.Identity).Claims;
        string role = claims.Where(claim => claim.Type.Split('/').LastOrDefault() == "role").FirstOrDefault().Value;
        userViewModel.Role = role;
        return View(userViewModel);
    }
    public async Task<IActionResult> ShoppingCart()
    {
        using (HttpClient client = new HttpClient())
        {
            client.BaseAddress = new Uri($"https://localhost:7091/api/ShoppingCartAPI/GetShoppingCart/{User.Identity.Name}");

            var response = await client.GetFromJsonAsync<List<Disk>>(client.BaseAddress);

            if (response is not null)
            {
                Console.WriteLine(response);
                return View(response);
            }
            else
            {
                return BadRequest();
            }
        }
        
    }

}

CRUDWithAccounts/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using CRUDWithAccounts.ViewModels;
using Database.Entity;
using Database;

namespace CRUDWithAccounts.Controllers;

[Authorize(Roles = "Admin")]
public class AdminController : Controller
{
    private readonly ILogger<AdminController> _logger;
    private readonly IDBRepository repository;

    public AdminController(ILogger<AdminController> logger, IDBRepository _repository)
    {
        _logger = logger;
        repository = _repository;
    }
  
    public IActionResult AdminPage()
    {
        var userViewModel = new UserWithRoleViewModel();
        userViewModel.Username = User.Identity.Name;
        var claims = ((ClaimsIdentity)User.Identity).Claims;
        string role = claims.Where(claim => claim.Type.Split('/').LastOrDefault() == "role").FirstOrDefault().Value;
        userViewModel.Role = role;
        return View(userViewModel);
    }
    public IActionResult AddDisk()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> AddDisk(DiskViewModel diskViewModel)
    {
        Disk diskToAdd = new Disk() {
            Manufacturer = diskViewModel.Manufacturer,
            Model = diskViewModel.Manufacturer,
            Type = diskViewModel.Type,
            Capacity = diskViewModel.Capacity,
            ReadSpeed = diskViewModel.ReadSpeed,
            WriteSpeed = diskViewModel.WriteSpeed,
            Cost = diskViewModel.ReadSpeed
        };
        await repository.AddDiskAsync(diskToAdd);
        return RedirectToAction("AddDiskPage");
    }
}

CRUDWithAccounts/Controllers/HomeController.cs
using System.Diagnostics;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using CRUDWithAccounts.Models;
using Database;
using Microsoft.AspNetCore.Authorization;

namespace CRUDWithAccounts.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IDBRepository repository;

    public HomeController(ILogger<HomeController> logger, IDBRepository _repository)
    {
        _logger = logger;
        repository = _repository;
    }

    public IActionResult Index(string? username)
    {
        return View(username);
    }


    public async Task<IActionResult> Catalog()
    {
        var list = await repository.GetAllDisksAsync();
        if (User.Identity.IsAuthenticated)
        {
            ViewData["Usename"] = User.Identity.Name;
            var claims = ((ClaimsIdentity)User.Identity).Claims;
            string role = claims.Where(claim => claim.Type.Split('/').LastOrDefault() == "role").FirstOrDefault().Value;
            ViewData["Role"] = role;
        }

        return View(list);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

CRUDWithAccounts/Views/AccountPage/AccountPage.cshtml
@{
    ViewData["Title"] = "User Page";
}

<h1>@Model.Role @Model.Username</h1>

<a asp-controller="AccountPage" asp-action="ShoppingCart">Корзина</a>

CRUDWithAccounts/Views/AccountPage/ShoppingCart.cshtml
@{
    ViewData["Title"] = "Shopping Cart";
}

<table class="table table-bordered">
    @{
        int totalPrice = 0;
        @foreach (var disk in Model)
        {
            <tr> 
                <td>@disk.Manufacturer</td>
                <td>@disk.Model</td>
                <td>@disk.Type</td>
                <td>@disk.Capacity</td>
                <td>@disk.ReadSpeed</td>
                <td>@disk.WriteSpeed</td>
                <td>@disk.Cost</td>
                <td><button class="button" onclick=deleteFromCart(@disk.Id) id="deleteFromCartButton-@disk.Id">Удалить из корзины</button></td>
            </tr>
            totalPrice += disk.Cost;
        }
        <span>Итоговая цена: @totalPrice тенге</span>
    }
    
</table>

@section Scripts {
    <script>
        async function deleteFromCart(_diskId) {
            let params = {
                diskId: _diskId,
                username: '@User.Identity.Name'
            };
            var response = await fetch(`https://localhost:7091/api/ShoppingCartAPI/DeleteFromShoppingCart/@User.Identity.Name/${_diskId}`, {
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json;charset=urf-8'
                },
                body: JSON.stringify(params)
            });
            if (response.status == 200) {
                document.getElementById("deleteFromCartButton-"+_diskId).innerText = "✓";
            }
        }
    </script>
}

CRUDWithAccounts/Views/Admin/AddDisk.cshtml
@model DiskViewModel
@{
    ViewData["Title"] = "Добавить диск";
}
<h1>Добавить диск в систему</h1>
<form class="form" asp-controller="Admin" asp-action="AddDisk" method="post">
    <div>
        <label>Производитель</label>
        <input type="text" asp-for="Manufacturer" class="form-control">
        <span asp-validation-for="Manufacturer"></span>
        <label>Модель</label>
        <input type="Text" asp-for="Model" class="form-control">
        <span asp-validation-for="Model"></span>
        <label>Тип</label>
        <input type="Text" asp-for="Type" class="form-control">
        <span asp-validation-for="Model"></span>
        <label>Размер памяти</label>
        <input type="number" asp-for="Capacity" class="form-control">
        <span asp-validation-for="Capacity"></span>
        <label>Скорость чтения</label>
        <input type="number" asp-for="ReadSpeed" class="form-control">
        <span asp-validation-for="ReadSpeed"></span>
        <label>Скорость записи</label>
        <input type="number" asp-for="WriteSpeed" class="form-control">
        <span asp-validation-for="WriteSpeed"></span>
        <label>Стоимость</label>
        <input type="number" asp-for="Cost" class="form-control">
        <span asp-validation-for="Cost"></span>
        <button type="submit" class="btn-success">Добавить диск</button>
    </div>
</form>

CRUDWithAccounts/Views/Admin/AdminPage.cshtml
@{
    ViewData["Title"] = "Страница администратора";
}

<h1>@Model.Role @Model.Username</h1>

<a asp-controller="Admin" asp-action="AddDisk">Добавить диск</a>

CRUDWithAccounts/Views/Home/Catalog.cshtml
@{
    ViewData["Title"] = "Catalog";
}
@if (User.Identity.IsAuthenticated & ViewData["Role"].ToString() == "User")
{
    @section Scripts {
    <script>
        async function addToCart(_diskId) {
            let params = {
                diskId: _diskId,
                username: '@ViewData["Username"]'
            };
            var response = await fetch(`https://localhost:7091/api/ShoppingCartAPI/AddToShoppingCart/${_diskId}/@User.Identity.Name`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json;charset=urf-8'
                },
                body: JSON.stringify(params)
            });
            if (response.status == 200) {
                document.getElementById("addToCartButton-"+_diskId).innerText = "✓";
            }
        }
    </script>
    }
}
@if (User.Identity.IsAuthenticated & ViewData["Role"].ToString() == "Admin")
{
    @section Scripts {
    <script>
        async function deleteDisk(_diskId) {
            let params = {
                diskId: _diskId,
            };
            var response = await fetch(`https://localhost:7091/api/DiskStoreAPI/DeleteDisk/${_diskId}`, {
                method: 'DELETE',
                headers: {
                    'Content-Type': 'application/json;charset=urf-8'
                },
                body: JSON.stringify(params)
            });
            if (response.status == 200) {
                document.getElementById("deleteDiskButton-"+_diskId).innerText = "✓";
            }
        }
    </script>
    }
}


<h1>@ViewData["Title"]</h1>
<table class="table table-bordered">
    @foreach (var disk in Model)
    {
        <tr>
            <td>@disk.Id</td>      
            <td>@disk.Manufacturer</td>
            <td>@disk.Model</td>
            <td>@disk.Type</td>
            <td>@disk.Capacity</td>
            <td>@disk.ReadSpeed</td>
            <td>@disk.WriteSpeed</td>
            <td>@disk.Cost</td>
            @if (User.Identity.IsAuthenticated)
            {
                @if (ViewData["Role"].ToString() == "User")
                {
                    <td><button class="button" onclick=addToCart(@disk.Id) id="addToCartButton-@disk.Id">Добавить в корзину</button></td>
                }
                @if (ViewData["Role"].ToString() == "Admin")
                {
                    <td><button class="button" onclick=deleteDisk(@disk.Id) id="deleteDiskButton-@disk.Id">Удалить диск</button></td>
                }
            }
        </tr>
    }
</table>

CRUDWithAccounts/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Добро пожаловать в наш магазин дисков!</h1>
</div>

CRUDWithAccounts/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDWithAccounts</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CRUDWithAccounts.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUDWithAccounts</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Catalog">Catalog</a>
                        </li>
                        @if (User.Identity.IsAuthenticated )
                        {
                            @if (User.IsInRole("User"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="AccountPage" asp-action="AccountPage">@User.Identity.Name</a>
                                </li>
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AdminPage">@User.Identity.Name</a>
                                </li>
                            }
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else 
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CRUDWithAccounts - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>